// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIQIH-oCDo-6HNP0FpXrPnPJqGp4L5dg0',
    appId: '1:499694091926:web:1969a91edc41ab54454cb7',
    messagingSenderId: '499694091926',
    projectId: 'flutter-sample-2deaa',
    authDomain: 'flutter-sample-2deaa.firebaseapp.com',
    storageBucket: 'flutter-sample-2deaa.appspot.com',
    measurementId: 'G-QZTZ05ERSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs40uGxyaUlWpNfIVz4rqpdWTvMtdneF8',
    appId: '1:499694091926:android:99be736f77a86fe6454cb7',
    messagingSenderId: '499694091926',
    projectId: 'flutter-sample-2deaa',
    storageBucket: 'flutter-sample-2deaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_y9Sc1_oXVFr53tLwXW-OZKXfcdxN5Q',
    appId: '1:499694091926:ios:87ca124990b8fc75454cb7',
    messagingSenderId: '499694091926',
    projectId: 'flutter-sample-2deaa',
    storageBucket: 'flutter-sample-2deaa.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_y9Sc1_oXVFr53tLwXW-OZKXfcdxN5Q',
    appId: '1:499694091926:ios:d967c315522e7f25454cb7',
    messagingSenderId: '499694091926',
    projectId: 'flutter-sample-2deaa',
    storageBucket: 'flutter-sample-2deaa.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
